const fs = require('fs');
const path = require('path');

const mc = (number, passage, text, options, correctAnswer, difficulty, subcategory, subcategoryId, explanation, graphAsset = null, graphDescription = null) => ({
  originalQuestionNumber: number,
  passage,
  text,
  questionType: 'multiple-choice',
  options,
  correctAnswer,
  acceptedAnswers: null,
  difficulty,
  subcategory,
  subcategoryId,
  explanation,
  graphAsset,
  graphDescription,
});

const spr = (number, passage, text, correctAnswer, acceptedAnswers, difficulty, subcategory, subcategoryId, explanation, graphAsset = null, graphDescription = null) => ({
  originalQuestionNumber: number,
  passage,
  text,
  questionType: 'user-input',
  options: [],
  correctAnswer,
  acceptedAnswers,
  difficulty,
  subcategory,
  subcategoryId,
  explanation,
  graphAsset,
  graphDescription,
});

const module3 = [
  mc(
    1,
    null,
    'The x-coordinate of each point on a line is 17 less than 4 times its y-coordinate. Which equation represents the line?',
    ['x = 4y - 17', 'x = 4y + 17', 'y = 4x - 17', 'y = 4x + 17'],
    0,
    'easy',
    'linear-equations-two-variables',
    13,
    'Choice A is correct. The phrase “17 less than 4 times its y-coordinate” means subtract 17 from 4y, so x = 4y - 17. Choice B is incorrect because it adds 17 instead of subtracting 17. Choices C and D are incorrect because they make y, rather than x, the quantity described as 17 less than or greater than 4 times the other coordinate.'
  ),
  mc(
    2,
    '<div style="text-align:center; margin:8px 0;">2x(x + 5) - x(x - 1)</div>',
    'Which expression is equivalent to the given expression?',
    ['x² + 9x', 'x² + 10x', 'x² + 11x', '3x² + 9x'],
    2,
    'easy',
    'equivalent-expressions',
    18,
    'Choice C is correct. Distributing gives 2x² + 10x - (x² - x). Subtracting the second quantity changes both of its signs, so the result is 2x² + 10x - x² + x = x² + 11x. Choice A does not change the sign of the -x term inside the second product. Choice B omits the +x produced when x(x - 1) is subtracted. Choice D combines the x² terms by addition rather than subtraction.'
  ),
  mc(
    3,
    '<p>A technician recorded the number of recalibration attempts required for each of 20 pressure gauges. The results are shown.</p>',
    'What is the range of the numbers of recalibration attempts?',
    ['1', '5', '6', '20'],
    1,
    'easy',
    'one-variable-data',
    21,
    'Choice B is correct. The least number of recalibration attempts shown is 1, and the greatest is 6. The range is 6 - 1 = 5. Choice A is incorrect because 1 is the minimum data value, not the range. Choice C is incorrect because 6 is the maximum data value, not the range. Choice D is incorrect because 20 is the total number of gauges represented.',
    'PT10-M3-Q03.svg',
    'A bar graph titled Recalibration Attempts has a horizontal axis labeled Number of attempts with values 1 through 6 and a vertical axis labeled Number of gauges. The bar heights for 1, 2, 3, 4, 5, and 6 attempts are 2, 5, 6, 4, 2, and 1, respectively.'
  ),
  mc(
    4,
    '<div style="text-align:center; margin:8px 0;">7(x - 2) = 3x + 18</div>',
    'What is the solution to the given equation?',
    ['2', '4', '6', '8'],
    3,
    'easy',
    'linear-equations-one-variable',
    11,
    'Choice D is correct. Distributing 7 gives 7x - 14 = 3x + 18. Subtracting 3x from both sides and adding 14 to both sides gives 4x = 32, so x = 8. Choices A, B, and C are incorrect because substituting 2, 4, or 6 for x does not make the two sides of the equation equal.'
  ),
  spr(
    5,
    null,
    'A triangular acoustic panel has a base of 22 inches and a perpendicular height of 8 inches. What is the area, in square inches, of the panel?',
    '88',
    ['88'],
    'easy',
    'area-volume',
    26,
    'The correct answer is 88. The area A of a triangle is one-half the product of its base b and perpendicular height h, so A = (1/2)bh. Substituting b = 22 and h = 8 gives A = (1/2)(22)(8) = 88 square inches. Adding the side lengths or using 22(8) without the factor of one-half would not give the area of the triangular panel.'
  ),
  spr(
    6,
    '<div style="text-align:center; margin:8px 0;">(3/5)x + 7 = 19</div>',
    'If x satisfies the given equation, what is the value of 3x?',
    '60',
    ['60'],
    'easy',
    'linear-equations-one-variable',
    11,
    'The correct answer is 60. Subtracting 7 from both sides gives (3/5)x = 12. Multiplying both sides by 5 gives 3x = 60. This is the quantity requested, so it is not necessary to divide by 3. Equivalently, solving completely gives x = 20, and then 3x = 3(20) = 60. Reporting 20 would give x rather than the requested value of 3x.'
  ),
  mc(
    7,
    '<p>The graph of the function f is shown.</p>',
    'Which equation could define f?',
    ['f(x) = x² - 1', 'f(x) = x² + 1', 'f(x) = -x² + 1', 'f(x) = (x - 1)²'],
    1,
    'easy',
    'nonlinear-functions',
    16,
    'Choice B is correct. The graph opens upward, is symmetric about the y-axis, and has vertex (0, 1). These features agree with f(x) = x² + 1. Choice A is incorrect because its vertex is (0, -1). Choice C is incorrect because its graph opens downward. Choice D is incorrect because its vertex is (1, 0).',
    'PT10-M3-Q07.svg',
    'A coordinate plane shows a smooth upward-opening parabola labeled f. Its vertex is at (0, 1), and it passes through (-2, 5), (-1, 2), (1, 2), and (2, 5).'
  ),
  mc(
    8,
    '<div style="text-align:center; margin:8px 0;">x + 2y = 7</div><div style="text-align:center; margin:8px 0;">3x - y = 7</div>',
    'Which ordered pair (x, y) is the solution to the given system of equations?',
    ['(3, 2)', '(2, 3)', '(1, 3)', '(2, -1)'],
    0,
    'easy',
    'systems-linear-equations',
    14,
    'Choice A is correct. For (3, 2), the first equation gives 3 + 2(2) = 7 and the second gives 3(3) - 2 = 7, so the pair satisfies both equations. Choice B is incorrect because it reverses the coordinates of the solution. Choice C satisfies the first equation but not the second. Choice D satisfies the second equation but not the first.'
  ),
  mc(
    9,
    null,
    'A laser cutter completes 7 identical paths in 12.6 minutes at a constant rate. At this rate, how many minutes will it take the cutter to complete 15 paths?',
    ['1.8', '12.6', '25.2', '27'],
    3,
    'easy',
    'ratios-rates-proportions',
    19,
    'Choice D is correct. Dividing 12.6 minutes by 7 paths gives 1.8 minutes per path. At this rate, 15 paths take 15(1.8) = 27 minutes. Choice A is the time for one path. Choice B is the time for the original 7 paths. Choice C doubles the original time, which accounts for 14 paths at the constant rate rather than the requested 15 paths.'
  ),
  mc(
    10,
    '<div style="text-align:center; margin:8px 0;">|3x - 5| = x + 7</div>',
    'Which pair lists all solutions to the given equation?',
    ['(-1/2, 11/2)', '(-3, 6)', '(-1/2, 6)', '(1/2, 6)'],
    2,
    'medium',
    'nonlinear-equations',
    17,
    'Choice C is correct. If 3x - 5 is nonnegative, then 3x - 5 = x + 7, which gives x = 6. If 3x - 5 is negative, then -(3x - 5) = x + 7, which gives -3x + 5 = x + 7 and x = -1/2. Both values satisfy the original equation. Choice A uses the sum of the solutions as a solution. Choice B uses the product of the solutions as a solution. Choice D changes the sign of the negative solution.'
  ),
  mc(
    11,
    null,
    'A utility will estimate the proportion of its 18,000 streetlights that need a lens replacement. Plan A uses a simple random sample of 250 streetlights, and plan B uses a simple random sample of 1,000 streetlights. Which statement is most likely true?',
    ['The estimate from plan B will have a smaller margin of error than the estimate from plan A.', 'The estimate from plan A will have a smaller margin of error because fewer streetlights are inspected.', 'The two estimates will have the same margin of error because they are taken from the same population.', 'The estimate from plan B will equal the exact population proportion because its sample is larger.'],
    0,
    'medium',
    'inference-statistics',
    24,
    'Choice A is correct. When random samples are taken in the same way from the same population, a larger sample generally produces less sampling variability and a smaller margin of error. Choice B reverses this relationship. Choice C is incorrect because sample size affects margin of error even when the population is the same. Choice D is incorrect because a random sample estimate can still differ from the exact population proportion.'
  ),
  spr(
    12,
    '<div style="text-align:center; margin:8px 0;">(2x<sup>2</sup> + kx + 15)/(2x + 5) = x + 3</div>',
    'The given equation is true for all x ≠ -5/2, where k is a constant. What is the value of k?',
    '11',
    ['11'],
    'medium',
    'equivalent-expressions',
    18,
    'The correct answer is 11. Multiplying both sides by 2x + 5 gives 2x² + kx + 15 = (2x + 5)(x + 3). Expanding the right side gives 2x² + 11x + 15. Since the equality holds for every allowed value of x, corresponding coefficients must be equal, so k = 11. With this value, the numerator factors as (2x + 5)(x + 3), confirming the quotient for x ≠ -5/2.'
  ),
  spr(
    13,
    '<p>The scatterplot shows measurements from eight fan settings and a line of best fit.</p>',
    'What is the slope of the line of best fit shown?',
    '5/2',
    ['5/2'],
    'medium',
    'two-variable-data',
    22,
    'The correct answer is 5/2. The two open, marked points on the line of best fit are (2, 8) and (8, 23). Slope is the change in the vertical coordinate divided by the corresponding change in the horizontal coordinate. Therefore, the slope is (23 - 8)/(8 - 2) = 15/6 = 5/2, which is also 2.5. Using individual scatterplot points instead of two points on the fitted line would not determine the displayed line’s exact slope.',
    'PT10-M3-Q13.svg',
    'A scatterplot has a horizontal axis labeled Fan setting from 0 to 9 and a vertical axis labeled Airflow from 0 to 26. The eight plotted points are (1, 6), (2, 9), (3, 10), (4, 14), (5, 15), (6, 19), (7, 20), and (8, 24). A line of best fit passes through the marked points (2, 8) and (8, 23).'
  ),
  mc(
    14,
    '<div style="text-align:center; margin:8px 0;">(k + 2)x - 3y = 18</div>',
    'The line defined by the given equation passes through the point (3, -1). What is the value of k?',
    ['-3', '-1', '1', '3'],
    3,
    'medium',
    'linear-equations-two-variables',
    13,
    'Choice D is correct. Substituting x = 3 and y = -1 gives 3(k + 2) - 3(-1) = 18. Thus, 3k + 9 = 18, so 3k = 9 and k = 3. Choice A makes the left side 0, Choice B makes it 6, and Choice C makes it 12. None equals the required right side of 18.'
  ),
  mc(
    15,
    '<p>In the figure, the angle labeled (7x - 5)° is an exterior angle of the triangle.</p>',
    'What is the measure, in degrees, of the exterior angle?',
    ['10', '60', '65', '115'],
    2,
    'medium',
    'lines-angles-triangles',
    27,
    'Choice C is correct. An exterior angle of a triangle equals the sum of the two nonadjacent interior angles. Therefore, 7x - 5 = (3x + 5) + (2x + 10). Solving gives 2x = 20, so x = 10. The exterior angle is 7(10) - 5 = 65°. Choice A is the value of x, not the requested angle. Choice B results from omitting the +5 in the expression 3x + 5 when adding the two remote interior angles after finding x. Choice D is the adjacent interior angle, which is supplementary to the 65° exterior angle.',
    'PT10-M3-Q15.svg',
    'A triangle has its left interior angle labeled (3x + 5) degrees and its top interior angle labeled (2x + 10) degrees. At the right vertex, one side is extended to form an exterior angle labeled (7x - 5) degrees. The figure is not drawn to scale.'
  ),
  mc(
    16,
    '<p>The graph of a function f contains the point (2, -5). The function g is defined by g(x) = f(x - 4) + 3.</p>',
    'Which point must lie on the graph of g?',
    ['(-2, -2)', '(6, -2)', '(-2, -8)', '(6, -8)'],
    1,
    'medium',
    'nonlinear-functions',
    16,
    'Choice B is correct. To use the known value f(2) = -5, set x - 4 = 2, which gives x = 6. Then g(6) = f(2) + 3 = -5 + 3 = -2, so (6, -2) lies on the graph of g. Choices A and C reverse the horizontal shift. Choices C and D subtract 3 from the output instead of adding 3.'
  ),
  mc(
    17,
    '<div style="text-align:center; margin:8px 0;">x<sup>2</sup> + y<sup>2</sup> - 8x + 6y = 0</div>',
    'The graph of the given equation is a circle. A line tangent to the circle at (8, 0) crosses the y-axis at (0, b). What is the value of b?',
    ['-4/3', '3/4', '8', '32/3'],
    3,
    'hard',
    'circles',
    29,
    'Choice D is correct. Completing the square gives (x - 4)² + (y + 3)² = 25, so the center is (4, -3). The slope of the radius from (4, -3) to (8, 0) is 3/4, so the tangent slope is the negative reciprocal, -4/3. A line with this slope through (8, 0) is y = (-4/3)(x - 8) = (-4/3)x + 32/3. Therefore, b = 32/3. Choice A is the tangent slope, Choice B is the radius slope, and Choice C is the x-coordinate of the tangency point.'
  ),
  mc(
    18,
    '<p>During a test, the temperature T(t), in degrees Celsius, of a thermal chamber changes linearly with time t. For a constant k, T(2) = 3k + 7, T(8) = k - 5, and T(14) = -2k + 13.</p>',
    'What is the value of T(5)?',
    ['97', '61', '30', '-12'],
    1,
    'hard',
    'linear-functions',
    12,
    'Choice B is correct. The t-values are equally spaced, so the changes in T must be equal: (k - 5) - (3k + 7) = (-2k + 13) - (k - 5). This gives -2k - 12 = -3k + 18, so k = 30. Thus, T(2) = 97 and T(8) = 25, giving slope (25 - 97)/(8 - 2) = -12. Since 5 is 3 units after 2, T(5) = 97 + 3(-12) = 61. Choice A is T(2), Choice C is k, and Choice D is the slope.'
  ),
  spr(
    19,
    '<div style="text-align:center; margin:8px 0;">3x + 2y = 8</div><div style="text-align:center; margin:8px 0;">5x - 2y = 6</div>',
    'The solution to the given system is (x, y). What is the value of y - x?',
    '-3/8',
    ['-3/8'],
    'hard',
    'systems-linear-equations',
    14,
    'The correct answer is -3/8. Adding the equations eliminates y and gives 8x = 14, so x = 7/4. Substituting into 3x + 2y = 8 gives 21/4 + 2y = 32/4, so 2y = 11/4 and y = 11/8. Therefore, y - x = 11/8 - 14/8 = -3/8, which is -0.375. The order in the requested difference matters: x - y would have the opposite sign.'
  ),
  mc(
    20,
    '<p>Data set A has mean 14 and standard deviation s. Data set B is formed by replacing every value a in data set A with 3a - 2.</p>',
    'Which statement correctly gives the mean and standard deviation of data set B?',
    ['The mean is 40, and the standard deviation is 3s.', 'The mean is 40, and the standard deviation is 3s - 2.', 'The mean is 42, and the standard deviation is 3s.', 'The mean is 42, and the standard deviation is 3s - 2.'],
    0,
    'hard',
    'one-variable-data',
    21,
    'Choice A is correct. Multiplying every value by 3 and then subtracting 2 changes the mean to 3(14) - 2 = 40. Multiplying by 3 also multiplies the standard deviation by 3, but subtracting the same constant from every value does not change the spread, so the new standard deviation is 3s. Choices B and D incorrectly subtract 2 from the standard deviation. Choices C and D omit the subtraction of 2 when transforming the mean.'
  ),
  mc(
    21,
    '<p>The function f is quadratic and f(2) = f(14).</p><p>I. The axis of symmetry of the graph of f is x = 8.<br>II. f(5) = f(11).</p>',
    'Which of the statements must be true?',
    ['I only', 'II only', 'I and II', 'Neither I nor II'],
    2,
    'hard',
    'nonlinear-functions',
    16,
    'Choice C is correct. Equal output values of a quadratic occur at inputs equidistant from its axis of symmetry. Since 2 and 14 have midpoint (2 + 14)/2 = 8, statement I must be true. The inputs 5 and 11 are each 3 units from 8, so f(5) = f(11), and statement II must also be true. Choices A and B omit one statement that must be true, and Choice D omits both.'
  ),
  spr(
    22,
    '<div style="text-align:center; margin:8px 0;">√(x + 18) = x + a</div>',
    'In the given equation, a is a positive integer. If the equation has exactly one real solution, what is the greatest possible value of a?',
    '17',
    ['17'],
    'hard',
    'nonlinear-equations',
    17,
    'The correct answer is 17. Let u = √(x + 18), so u is nonnegative and x = u² - 18. Substitution gives u² - u + (a - 18) = 0. If a is at most 17, the product of the two roots is negative, so exactly one root is nonnegative and yields one real x. At a = 18, the roots are 0 and 1, yielding two solutions. For positive integers a greater than 18, there are no nonnegative roots; in particular, the discriminant is already negative at a = 19. Therefore, the greatest possible value is 17.'
  ),
];

const module4 = [
  mc(
    1,
    null,
    'A weather station records a wind speed of 2.4 meters per second. What is this speed, in centimeters per minute? (1 meter = 100 centimeters and 1 minute = 60 seconds)',
    ['240', '14,400', '144,000', '864,000'],
    1,
    'easy',
    'ratios-rates-proportions',
    19,
    'Choice B is correct. Multiplying 2.4 meters per second by 100 centimeters per meter gives 240 centimeters per second. Multiplying by 60 seconds per minute gives 14,400 centimeters per minute. Choice A performs only the meter-to-centimeter conversion. Choice C introduces an extra factor of 10. Choice D uses 3,600 seconds rather than 60 seconds for one minute.'
  ),
  mc(
    2,
    null,
    'A rectangular electronic display is 12 feet wide and 8 feet high. It is assembled without gaps from square display panels that each have a side length of 2 feet. How many panels are used?',
    ['6', '10', '20', '24'],
    3,
    'easy',
    'area-volume',
    26,
    'Choice D is correct. The display has area 12 × 8 = 96 square feet, and each panel has area 2² = 4 square feet. Therefore, 96/4 = 24 panels are used. Choice A divides only the width by the panel side length. Choice B divides the sum of the display dimensions by 2. Choice C is based on the display’s perimeter rather than its area.'
  ),
  mc(
    3,
    '<div style="text-align:center; margin:8px 0;">f(x) = 3 + √(x + 7)</div>',
    'What is the value of f(9)?',
    ['7', '12', '16', '19'],
    0,
    'easy',
    'nonlinear-functions',
    16,
    'Choice A is correct. Substituting 9 for x gives f(9) = 3 + √(9 + 7) = 3 + √16 = 3 + 4 = 7. Choice B replaces the entire radical √(9 + 7) with the input value 9 before adding 3. Choice C gives the quantity inside the square root without taking its square root or adding 3. Choice D adds 3, 9, and 7 without taking a square root.'
  ),
  mc(
    4,
    '<div style="text-align:center; margin:8px 0;">(18x<sup>7</sup>y<sup>3</sup>)/(6x<sup>2</sup>y)</div>',
    'Which expression is equivalent to the given expression?',
    ['3x⁵y³', '12x⁵y²', '3x⁵y²', '3x⁹y⁴'],
    2,
    'easy',
    'equivalent-expressions',
    18,
    'Choice C is correct. Dividing the coefficients gives 18/6 = 3. For like bases, subtracting exponents gives x^(7-2) = x⁵ and y^(3-1) = y². Thus, the quotient is 3x⁵y². Choice A does not subtract the y-exponents. Choice B subtracts the coefficients instead of dividing them. Choice D adds the exponents instead of subtracting them.'
  ),
  spr(
    5,
    '<div style="text-align:center; margin:8px 0;">2x + y = 17</div><div style="text-align:center; margin:8px 0;">2x - y = 7</div>',
    'The solution to the given system is (x, y). What is the value of y?',
    '5',
    ['5'],
    'easy',
    'systems-linear-equations',
    14,
    'The correct answer is 5. Subtracting the second equation from the first eliminates the identical 2x terms: (2x + y) - (2x - y) = 17 - 7. This simplifies to 2y = 10, so y = 5. Adding the equations would instead give 4x = 24 and x = 6. Substitution verifies the result because 2(6) + 5 = 17 and 2(6) - 5 = 7.'
  ),
  spr(
    6,
    null,
    'An additive makes up 15% of the mass of a 250-gram material sample. What is the mass, in grams, of the additive?',
    '37.5',
    ['37.5'],
    'easy',
    'percentages',
    20,
    'The correct answer is 37.5. Fifteen percent is 15/100, or 0.15. Multiplying the total sample mass by this proportion gives 0.15(250) = 37.5 grams. The value 37.5 is equivalent to 75/2. Subtracting 15 from 250 or using 15 as a decimal multiplier would not represent 15% of the sample’s mass.'
  ),
  mc(
    7,
    '<p>The graph shows the energy E, in watt-hours, stored in a backup battery t hours after charging begins.</p>',
    'How many watt-hours of energy were stored in the battery when charging began?',
    ['0', '5', '15', '30'],
    3,
    'easy',
    'linear-functions',
    12,
    'Choice D is correct. Charging begins when t = 0. The graph crosses the vertical E-axis at 30, so 30 watt-hours were stored when charging began. Choice A is the input value at the start. Choice B is the hourly rate of increase shown by the line. Choice C is the increase over the first 3 hours, not the initial amount.',
    'PT10-M4-Q07.svg',
    'A coordinate graph has a horizontal axis labeled Time (hours), t, from 0 to 5 and a vertical axis labeled Energy (watt-hours), E, from 0 to 55. A straight line passes through the marked points (0, 30) and (3, 45).'
  ),
  mc(
    8,
    '<p>The table shows values of a quadratic function f.</p><table style="border-collapse:collapse; margin:10px auto; text-align:center;"><caption style="padding:4px; font-weight:bold;">Values of f</caption><tr><th scope="row" style="border:1px solid #000; padding:6px 11px;">x</th><th scope="col" style="border:1px solid #000; padding:6px 11px;">-1</th><th scope="col" style="border:1px solid #000; padding:6px 11px;">0</th><th scope="col" style="border:1px solid #000; padding:6px 11px;">1</th><th scope="col" style="border:1px solid #000; padding:6px 11px;">2</th><th scope="col" style="border:1px solid #000; padding:6px 11px;">3</th></tr><tr><th scope="row" style="border:1px solid #000; padding:6px 11px;">f(x)</th><td style="border:1px solid #000; padding:6px 11px;">8</td><td style="border:1px solid #000; padding:6px 11px;">3</td><td style="border:1px solid #000; padding:6px 11px;">0</td><td style="border:1px solid #000; padding:6px 11px;">-1</td><td style="border:1px solid #000; padding:6px 11px;">0</td></tr></table>',
    'At which value of x shown in the table does f(x) have its minimum value?',
    ['1', '2', '3', '4'],
    1,
    'easy',
    'nonlinear-functions',
    16,
    'Choice B is correct. The least output shown is -1, and it occurs when x = 2. Choice A is incorrect because f(1) = 0. Choice C is incorrect because f(3) = 0. Choice D is incorrect because x = 4 is not one of the inputs shown in the table.'
  ),
  mc(
    9,
    null,
    'An equipment rack can support at most 680 pounds. Equipment already on the rack has a total mass of 125 pounds, and each additional unit has a mass of 37 pounds. If n additional units are placed on the rack, which inequality represents this situation?',
    ['37 + 125n ≤ 680', '125 + 37n ≥ 680', '125 + 37n ≤ 680', '37n ≤ 680'],
    2,
    'easy',
    'linear-inequalities',
    15,
    'Choice C is correct. The total load is the existing 125 pounds plus 37 pounds for each of n additional units, or 125 + 37n. The phrase “at most 680” means this total is less than or equal to 680. Choice A reverses the roles of 125 and 37. Choice B uses the wrong inequality direction. Choice D omits the equipment already on the rack.'
  ),
  mc(
    10,
    '<p>The intensity of a signal d meters from a transmitter is modeled by S(d) = 320(0.90)<sup>d/5</sup>.</p>',
    'According to the model, for each 10-meter increase in d, the signal intensity decreases by what percent?',
    ['81%', '20%', '19%', '10%'],
    2,
    'medium',
    'nonlinear-functions',
    16,
    'Choice C is correct. Increasing d by 10 increases the exponent d/5 by 2, so the intensity is multiplied by (0.90)² = 0.81. The new intensity is 81% of the previous intensity, which is a 19% decrease. Choice A gives the percent that remains. Choice B doubles 10% without accounting for compounding. Choice D is the decrease for a 5-meter increase, not a 10-meter increase.'
  ),
  mc(
    11,
    '<div style="text-align:center; margin:8px 0;">ky &gt; 171</div><p>The solution set of the given inequality is graphed in the xy-plane, where k is a positive constant.</p>',
    'What is the value of k?',
    ['9', '19', '171', '180'],
    1,
    'medium',
    'linear-inequalities',
    15,
    'Choice B is correct. Because k is positive, dividing ky > 171 by k gives y > 171/k. The graph has a dashed boundary at y = 9 and is shaded above it, so 171/k = 9. Therefore, k = 171/9 = 19. Choice A is the boundary’s y-value. Choice C is the constant before division. Choice D results from adding 9 to 171 instead of dividing.',
    'PT10-M4-Q11.svg',
    'A coordinate plane shows a dashed horizontal line through y = 9. The half-plane above this line is shaded, and the half-plane below it is not shaded.'
  ),
  spr(
    12,
    '<div style="text-align:center; margin:8px 0;">2x<sup>2</sup> - 3x - 14 = 0</div>',
    'What is the positive solution to the given equation?',
    '7/2',
    ['7/2'],
    'medium',
    'nonlinear-equations',
    17,
    'The correct answer is 7/2. Factoring the quadratic gives (2x - 7)(x + 2) = 0 because the product expands to 2x² - 3x - 14. By the zero-product property, 2x - 7 = 0 or x + 2 = 0. Therefore, the solutions are x = 7/2 and x = -2. The question asks for the positive solution, so the answer is 7/2, which is 3.5.'
  ),
  spr(
    13,
    null,
    'In the xy-plane, a line has slope -3/2 and passes through the point (4, 9). What is the x-coordinate of the x-intercept of the line?',
    '10',
    ['10'],
    'medium',
    'linear-equations-two-variables',
    13,
    'The correct answer is 10. Using the given slope and point in point-slope form gives y - 9 = (-3/2)(x - 4). At the x-intercept, the y-coordinate is 0, so -9 = (-3/2)(x - 4). Multiplying both sides by -2/3 gives 6 = x - 4, and therefore x = 10. Substitution confirms that the line drops 9 units while moving 6 units to the right from (4, 9) to (10, 0).'
  ),
  mc(
    14,
    '<p>Triangle ABC is a right triangle. The side lengths shown are in centimeters.</p>',
    'What is the value of cos A?',
    ['40/41', '9/40', '9/41', '1/41'],
    0,
    'medium',
    'right-triangles-trigonometry',
    28,
    'Choice A is correct. The missing leg has length √(41² - 9²) = √1600 = 40. Relative to angle A, this leg is adjacent and the hypotenuse is 41, so cos A = 40/41. Choice B is the ratio of the two legs in the wrong order for a cosine. Choice C uses the opposite leg over the hypotenuse, which is sin A. Choice D uses the difference between the hypotenuse, 41, and the calculated adjacent leg, 40, as the numerator.',
    'PT10-M4-Q14.svg',
    'A right triangle ABC has a right angle at C. The hypotenuse AB is labeled 41, the leg BC is labeled 9, and the leg AC is unlabeled. Angle A is marked.'
  ),
  mc(
    15,
    null,
    'A container holds 18 brass tokens and 12 steel tokens. Steel tokens are added, and no tokens are removed. How many steel tokens must be added so that the probability of selecting a brass token at random is 1/3?',
    ['6', '12', '18', '24'],
    3,
    'medium',
    'probability',
    23,
    'Choice D is correct. If s steel tokens are added, there are still 18 brass tokens and 30 + s tokens in all. Thus, 18/(30 + s) = 1/3. Multiplying gives 54 = 30 + s, so s = 24. Choice A would make the probability 18/36 = 1/2. Choice B would make it 18/42 = 3/7. Choice C would make it 18/48 = 3/8.'
  ),
  mc(
    16,
    '<p>The volume V, in milliliters, of solution in an ultrasonic cleaner changes linearly with time t, in minutes. At t = 6, the volume is 74 milliliters, and at t = 14, the volume is 46 milliliters.</p>',
    'Which equation gives V in terms of t?',
    ['V = 95 + 3.5t', 'V = 74 - 3.5t', 'V = 95 - 3.5t', 'V = 74 - 28t'],
    2,
    'medium',
    'linear-functions',
    12,
    'Choice C is correct. The slope is (46 - 74)/(14 - 6) = -28/8 = -3.5. Using V = -3.5t + b and the point (6, 74) gives 74 = -21 + b, so b = 95. Therefore, V = 95 - 3.5t. Choice A has the wrong slope sign. Choice B uses the value at t = 6 as the y-intercept. Choice D uses the total change in volume as the rate of change.'
  ),
  mc(
    17,
    '<p>Circle A has equation (x - 2)<sup>2</sup> + (y + 1)<sup>2</sup> = 25. Circle B has center (9, -1) and is externally tangent to circle A.</p>',
    'Which equation represents circle B?',
    ['(x - 9)² + (y + 1)² = 2', '(x - 9)² + (y + 1)² = 4', '(x + 9)² + (y - 1)² = 4', '(x - 9)² + (y + 1)² = 25'],
    1,
    'hard',
    'circles',
    29,
    'Choice B is correct. Circle A has center (2, -1) and radius 5. The centers are 7 units apart, and externally tangent circles have center distance equal to the sum of their radii. Thus, circle B has radius 7 - 5 = 2, so its equation is (x - 9)² + (y + 1)² = 2² = 4. Choice A uses the radius instead of its square on the right side. Choice C has incorrect signs for the center. Choice D gives circle B the same radius as circle A.'
  ),
  mc(
    18,
    '<div style="text-align:center; margin:8px 0;">a(2x - 3) + 4 = 10x + b</div>',
    'In the given equation, a and b are constants. If the equation is true for all values of x, what is the value of a + b?',
    ['-6', '5', '11', '16'],
    0,
    'hard',
    'linear-equations-one-variable',
    11,
    'Choice A is correct. Expanding the left side gives 2ax - 3a + 4. For the equation to be true for all x, 2a = 10, so a = 5. The constant terms must also match, so b = -3(5) + 4 = -11. Thus, a + b = 5 + (-11) = -6. Choice B is a, Choice C is the magnitude of b, and Choice D is a - b.'
  ),
  spr(
    19,
    '<div style="text-align:center; margin:8px 0;">4<sup>x</sup> - 5(2<sup>x</sup>) + 4 = 0</div>',
    'What is the sum of all real solutions to the given equation?',
    '2',
    ['2'],
    'hard',
    'nonlinear-equations',
    17,
    'The correct answer is 2. Let u = 2ˣ, so 4ˣ = (2ˣ)² = u². The equation becomes u² - 5u + 4 = 0, which factors as (u - 1)(u - 4) = 0. If 2ˣ = 1, then x = 0. If 2ˣ = 4, then x = 2. The sum of the real solutions is 0 + 2 = 2.'
  ),
  mc(
    20,
    '<p>A scatterplot and its line of best fit, y = 2x + 5, are shown. Point P = (7, 20) is one of the data points. For a data point, the residual is the observed y-value minus the y-value predicted by the line of best fit.</p>',
    'Point Q has x-coordinate 7 and a residual equal to -2 times the residual of point P. What are the coordinates of point Q?',
    ['(7, 17)', '(7, 18)', '(7, 19)', '(7, 21)'],
    0,
    'hard',
    'two-variable-data',
    22,
    'Choice A is correct. At x = 7, the line predicts y = 2(7) + 5 = 19. Point P has residual 20 - 19 = 1, so point Q has residual -2(1) = -2. Therefore, Q has observed y-value 19 + (-2) = 17 and coordinates (7, 17). Choice B subtracts 2 from P’s observed value rather than from the predicted value. Choice C gives the predicted point with residual 0. Choice D adds 2 to the predicted value instead of using residual -2.',
    'PT10-M4-Q20.svg',
    'A scatterplot has eight points: (0, 4), (1, 8), (2, 8), (3, 12), (4, 12), (5, 16), (6, 16), and P = (7, 20). A line of best fit labeled y = 2x + 5 is drawn through the scatterplot.'
  ),
  mc(
    21,
    '<p>For triangles ABC and DEF, AB/DE = BC/EF.</p>',
    'Which additional statement is sufficient to prove that triangle ABC is similar to triangle DEF?',
    ['Angle A is congruent to angle D.', 'AC = DF.', 'Angle C is congruent to angle F.', 'Angle B is congruent to angle E.'],
    3,
    'hard',
    'lines-angles-triangles',
    27,
    'Choice D is correct. The given proportions relate the two sides that meet at B in triangle ABC to the two sides that meet at E in triangle DEF. If angle B is congruent to angle E, the included angles are equal, so the triangles are similar by the side-angle-side similarity criterion. Choices A and C give a nonincluded angle, which does not guarantee similarity with the two given side ratios. Choice B gives equality of the third sides, not the proportionality needed for side-side-side similarity.'
  ),
  spr(
    22,
    null,
    'The quadratic function f has zeros -1 and 7, and f(2) = 30. What is the maximum value of f?',
    '32',
    ['32'],
    'hard',
    'nonlinear-functions',
    16,
    'The correct answer is 32. Since the zeros are -1 and 7, f(x) = a(x + 1)(x - 7). Using f(2) = 30 gives 30 = a(3)(-5), so a = -2. The axis of symmetry is halfway between the zeros, at x = 3. Because a is negative, the parabola opens downward and the vertex gives its maximum. Thus, f(3) = -2(4)(-4) = 32. This value is greater than the given value f(2) = 30, as expected near the vertex.'
  ),
];

const data = {
  examSlug: 'exam10-math-v1',
  targetExamTitle: 'Exam 10',
  note: 'Original Math replacement modules for Practice Test 10. Authored from the supplied official-form and Question Bank measurements. Figures are in practiceTest10Math-assets and are inlined by replaceExam10Math.js.',
  modules: [
    {
      moduleNumber: 3,
      title: 'Exam 10, Module 3',
      description: 'Practice Test 10 - Math, Module 1 (22 questions)',
      section: 'Math',
      calculatorAllowed: true,
      timeLimit: 2100,
      questions: module3,
    },
    {
      moduleNumber: 4,
      title: 'Exam 10, Module 4',
      description: 'Practice Test 10 - Math, Module 2 (22 questions)',
      section: 'Math',
      calculatorAllowed: true,
      timeLimit: 2100,
      questions: module4,
    },
  ],
};

const output = path.join(__dirname, 'data', 'practiceTest10Math.json');
fs.writeFileSync(output, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
console.log(`Wrote ${output}`);
